Repository gwAdvNet20/gwAdvNet20.github.io, pull requests merged in 2020-05, with the labels that each got.

#22 Final Blog Assignment
  wiki/awsNodeJS/aws-node-js.md
  wiki/awsNodeJS/steps/step1.png
  wiki/awsNodeJS/steps/step10.png
  wiki/awsNodeJS/steps/step2.png
  wiki/awsNodeJS/steps/step3.png
  wiki/awsNodeJS/steps/step4.png
  wiki/awsNodeJS/steps/step5.png
  wiki/awsNodeJS/steps/step6.png
  wiki/awsNodeJS/steps/step7.png
  wiki/awsNodeJS/steps/step8.png
  wiki/awsNodeJS/steps/step9.png
Labels: merged

#23 typicalZookeeperScenarios
  wiki/typicalZookeeperScenarios/images/ConfigurationManagement.png
  wiki/typicalZookeeperScenarios/images/GroupMembership.png
  wiki/typicalZookeeperScenarios/typicalZookeeperScenarios.md
Labels: early

#24 Tech Blog 2 on Consul 101. Agents, Data-centers, and Services
  wiki/Consul101Blog/Consul101Blog.md
  wiki/Consul101Blog/beforeANDafterJoin.JPG
  wiki/Consul101Blog/consul_logo.png
  wiki/Consul101Blog/envSet.JPG
  wiki/Consul101Blog/healthyOnlyAfter.JPG
  wiki/Consul101Blog/server.JPG
  wiki/Consul101Blog/serviceA.JPG
  wiki/Consul101Blog/serviceB.JPG
  wiki/Consul101Blog/serviceRun1.JPG
  wiki/Consul101Blog/soloMembers.JPG
  wiki/Consul101Blog/syncweb.JPG
  wiki/Consul101Blog/warn.JPG
Labels: early

#25 A Comparison of Different AWS Elastic Load Balancer Offerings with EC2
  wiki/aws-ec2-load-balancers/alb-diagram.png
  wiki/aws-ec2-load-balancers/aws-ec2-load-balancers-blog-post.md
  wiki/aws-ec2-load-balancers/aws_graphic.png
  wiki/aws-ec2-load-balancers/balance.png
  wiki/aws-ec2-load-balancers/browser_graphic.png
  wiki/aws-ec2-load-balancers/classic_graphic.png
  wiki/aws-ec2-load-balancers/clb1.png
  wiki/aws-ec2-load-balancers/clb2.png
  wiki/aws-ec2-load-balancers/clb3.png
  wiki/aws-ec2-load-balancers/clb4.png
  wiki/aws-ec2-load-balancers/first.png
  wiki/aws-ec2-load-balancers/nginx.png
  wiki/aws-ec2-load-balancers/nlb1.png
  wiki/aws-ec2-load-balancers/nlb2.png
  wiki/aws-ec2-load-balancers/osi.png
  wiki/aws-ec2-load-balancers/sampleCode/alb/index1.html
  wiki/aws-ec2-load-balancers/sampleCode/alb/index2.html
  wiki/aws-ec2-load-balancers/sampleCode/clb/index1clb.html
  wiki/aws-ec2-load-balancers/sampleCode/clb/index1nginx.html
  wiki/aws-ec2-load-balancers/sampleCode/clb/index2clb.html
  wiki/aws-ec2-load-balancers/sampleCode/clb/index2nginx.html
  wiki/aws-ec2-load-balancers/sampleCode/nlb/index1.nginx-debian.html
  wiki/aws-ec2-load-balancers/sampleCode/nlb/index2.nginx-debian.html
  wiki/aws-ec2-load-balancers/second.png
  wiki/aws-ec2-load-balancers/success.png
  wiki/aws-ec2-load-balancers/table.pdf
Labels: early

#26 Tech Blog Submission: Ethan Baron and Catherine Meadows
  wiki/NGINX_Consul_LoadBalancing/images/allonlineconsul.png
  wiki/NGINX_Consul_LoadBalancing/images/allonlinenoconsul.png
  wiki/NGINX_Consul_LoadBalancing/images/consului.gif
  wiki/NGINX_Consul_LoadBalancing/images/flowchart1.png
  wiki/NGINX_Consul_LoadBalancing/images/flowchart2.png
  wiki/NGINX_Consul_LoadBalancing/images/loadbalancer.gif
  wiki/NGINX_Consul_LoadBalancing/images/node2offlineconsul.png
  wiki/NGINX_Consul_LoadBalancing/images/node2offlinenoconsul.png
  wiki/NGINX_Consul_LoadBalancing/images/raftconsul.png
  wiki/NGINX_Consul_LoadBalancing/loadBalancing.md
  wiki/http1-2httpsSSL/.DS_Store
  wiki/http1-2httpsSSL/images/.DS_Store
  wiki/http1-2httpsSSL/images/How_to_transfer_key_itself_safely2.png
  wiki/http1-2httpsSSL/images/How_to_transfer_key_itself_safely?.png
Labels: early

#28 Spring Boot Server Using Zookeeper
  wiki/zookeeper/docker-compose.yml
  wiki/zookeeper/images/IOhandler.png
  wiki/zookeeper/images/ZKConfig.PNG
  wiki/zookeeper/images/Znode.PNG
  wiki/zookeeper/images/replicated-ops.png
  wiki/zookeeper/images/server-status-nc.png
  wiki/zookeeper/images/status.png
  wiki/zookeeper/src/Application.java
  wiki/zookeeper/src/controller/RestController.java
  wiki/zookeeper/zookeeper.md
Labels: final

#30 Consul with Go Blog by Katie/Linnea/Sreya
  wiki/ConsulWithGoBlog/ConsulWithGoBlog.md
  wiki/ConsulWithGoBlog/code/index.html
  wiki/ConsulWithGoBlog/code/main.go
  wiki/ConsulWithGoBlog/screenshots/CONSUL_GET_PUT_CODE.png
  wiki/ConsulWithGoBlog/screenshots/CONSUL_INIT_CODE.png
  wiki/ConsulWithGoBlog/screenshots/MAIN.png
  wiki/ConsulWithGoBlog/screenshots/PROCESS_FORM.png
  wiki/ConsulWithGoBlog/screenshots/SETUP.png
  wiki/ConsulWithGoBlog/screenshots/WebInterfaceScreenshot.png
Labels: final

#31 Distributed Load Testing using AWS Cloud Services
  wiki/benchmark/1.PNG
  wiki/benchmark/10.PNG
  wiki/benchmark/2.PNG
  wiki/benchmark/3.PNG
  wiki/benchmark/4.PNG
  wiki/benchmark/5.PNG
  wiki/benchmark/6.PNG
  wiki/benchmark/7.PNG
  wiki/benchmark/8.PNG
  wiki/benchmark/9.PNG
  wiki/benchmark/benchmark.md
  wiki/benchmark/load1.png
  wiki/benchmark/load2.png
  wiki/benchmark/load3.png
  wiki/benchmark/load4.png
  wiki/benchmark/m5_large.png
  wiki/benchmark/r5_large.png
  wiki/benchmark/step1.png
  wiki/benchmark/step10.png
  wiki/benchmark/step11.png
  wiki/benchmark/step13.png
  wiki/benchmark/step2.png
  wiki/benchmark/step3.png
  wiki/benchmark/step4.png
  wiki/benchmark/step5.png
  wiki/benchmark/step6.png
  wiki/benchmark/step7.png
  wiki/benchmark/step8.png
  wiki/benchmark/step9.png
  wiki/benchmark/t2_large.png
  wiki/benchmark/t2_micro.png
  wiki/benchmark/table.PNG
  wiki/benchmark/website.png
Labels: final

#32 Service mesh blog post
  wiki/service_mesh/boundary.png
  wiki/service_mesh/chain.png
  wiki/service_mesh/config.png
  wiki/service_mesh/istio_mesh.png
  wiki/service_mesh/post.md
  wiki/service_mesh/scale.png
Labels: final
